version: '3.1'

services:

  mysql:
    environment:
      MYSQL_DATA_DIR : /data/db
    volumes:
      - ./mysql_data:/data/db


  manage-pro-backend:
    command: sh -c "mvn clean install -DskipTests && mvn spring-boot:run"
